apiVersion: v2
name: argocd-appset-secret-plugin
description: A Helm chart for adding a K8s Secret Plugin Generator to ApplicationSets
maintainers:
  - name: "jessebot"
    email: "jessebot@linux.com"
    url: "https://github.com/jessebot/"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: 0.5.0

# renovate: image=jessebot/argocd-appset-secret-plugin
appVersion: "v0.3.0"
